services:
# まだゲームサーバー作ってないので一旦コメントアウト
#   # ゲームサーバー（Go）
#   game-server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     environment:
#       - DOCKER_HOST=unix:///var/run/docker.sock
#     volumes:
#       # GoサーバーがDockerを操作できるようにソケットをマウント
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - game_external
#       - game_internal
#     depends_on:
#       - target-server

  # 攻撃対象サーバー（ゲームの敵）
  target-server:
    build:
      context: ./target
      dockerfile: Dockerfile
    container_name: target-server #cAdvisorでアクセスするために固定名を付与
    # リソース制限（攻略難易度の設定）
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: 64M
    networks:
      - game_internal  # 外部遮断ネットワークのみ接続
    restart: "no"      # 倒されたら自動再起動しない（ゲームサーバーが制御）

# 攻撃コンテナ
  attacker:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    environment:
      # 対象のホスト名がtarget-server、ポートが8080であることを攻撃コンテナに伝える
      - TARGET_URL=http://target-server:8080
    networks:
      - game_internal # 密室に入らないと標的を殴れません
    depends_on:
      - target-server

  # 監視用のcAdvisorコンテナ
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - game_external
# Prometheusコンテナ
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # フロントエンドやブラウザからアクセスするためのポート
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro # 設定ファイルをマウント
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus' # データを保存する場所
      - '--storage.tsdb.retention.time=1h' # ゲーム用なので、過去1時間分のデータだけを保持
    networks:
      - game_external # cadvisorや外部と通信するため

networks:
  # ゲームサーバー ↔ ブラウザ間の通信用（外部公開）
  game_external:
    driver: bridge

  # 攻撃コンテナ ↔ ターゲットサーバー間（外部遮断・必須）
  game_internal:
    driver: bridge
    internal: true  # インターネットへの経路を物理的に遮断
