apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      io.kompose.service: cadvisor
  template:
    metadata:
      labels:
        io.kompose.service: cadvisor
    spec:
      containers:
        - image: gcr.io/cadvisor/cadvisor:v0.47.2
          name: cadvisor
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
            - mountPath: /var/run
              name: var-run
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /var/lib/docker
              name: docker
              readOnly: true
            - mountPath: /dev/disk
              name: disk
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: var-run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker
        - name: disk
          hostPath:
            path: /dev/disk
