apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor.monitoring.svc.cluster.local:8080']
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
  namespace: monitoring
