apiVersion: v1
data:
  prometheus.yml: |-
    # prometheus/prometheus.yml
    global:
      scrape_interval: 5s # 5秒おきにデータを収集

    scrape_configs:
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor:8080'] # docker-compose内で繋がってるので、名前で指定
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
