apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  selector:
    io.kompose.service: api
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  type: ClusterIP
