apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: target-server
  name: target-server
spec:
  selector:
    io.kompose.service: target-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
